FROM ubuntu:xenial

RUN apt-get update -y && apt-get install -y \
    apt-utils \
    bzip2 \
    gcc \
    make \
    ncurses-dev \
    wget \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev

##############
#HTSlib 1.8  #
##############
ENV HTSLIB_INSTALL_DIR=/opt/htslib

WORKDIR /tmp
RUN wget https://github.com/samtools/htslib/releases/download/1.8/htslib-1.8.tar.bz2 && \
    tar --bzip2 -xvf htslib-1.8.tar.bz2

WORKDIR /tmp/htslib-1.8
RUN ./configure  --enable-plugins --prefix=$HTSLIB_INSTALL_DIR && \
    make && \
    make install && \
    cp $HTSLIB_INSTALL_DIR/lib/libhts.so* /usr/lib/

################
#Samtools 1.8  #
################
ENV SAMTOOLS_INSTALL_DIR=/opt/samtools

WORKDIR /tmp
RUN wget https://github.com/samtools/samtools/releases/download/1.8/samtools-1.8.tar.bz2 && \
    tar --bzip2 -xf samtools-1.8.tar.bz2

WORKDIR /tmp/samtools-1.8
RUN ./configure --with-htslib=$HTSLIB_INSTALL_DIR --prefix=$SAMTOOLS_INSTALL_DIR && \
    make && \
    make install

WORKDIR /

#RUN rm -R /tmp/samtools-1.8

RUN cp /opt/samtools/bin/* /usr/bin

RUN cp /opt/htslib/bin/* /usr/bin

#######
#tabix#
#######
#RUN ln -s $HTSLIB_INSTALL_DIR/bin/tabix /usr/bin/tabix
